### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by Srijancse-zz** [stratdi/threespot.js#2]
Looks like the version is still very old, and it needs to be updated.

**Comment by iboutsi** [comment]
They are working. It needs to be downloaded and saved in the local server directory. For example for apache, save the file in htdocs and then open it directly from your browser typing: localhost/threespot.js-master
![capture](https://user-images.githubusercontent.com/36188620/41190778-80b9da16-6bed-11e8-89b9-2836269e7f61.JPG)
